version: '3.9'

services:
  freedev:
    build: 
      context: .
      dockerfile: Dockerfile
    tty: true
    ports:
      - '3000:3000'
    volumes:
      - $PWD:$PWD
    working_dir: $PWD
    extra_hosts:
      - host.docker.internal:host-gateway

  freedev-mysql:
    image: mysql:latest
    env_file:
      - ../.env
    volumes:
      - ./docker/mysql:/var/lib/mysql
    ports:
      - 3306:3306
    restart: always
    tty: true